#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# save payload in tmp for later inspection
cat > /tmp/payload <&0

# print input
payload=$(cat /tmp/payload)

# extract parameters
OPSMAN_IP_ADDRESS=$(echo $payload | jq -r ".source.OPSMAN_ADDRESS")
OPS_MGR_USR=$(echo $payload | jq -r ".source.OPSMAN_USERNAME")
OPS_MGR_PWD=$(echo $payload | jq -r ".source.OPSMAN_PASSWORD")
IAAS=$(echo $payload | jq -r ".source.IAAS")
PIVNET_TOKEN=$(echo $payload | jq -r ".source.PIVNET_TOKEN")
EXCLUDE_TILE_LIST=$(echo $payload | jq -r ".source.EXCLUDE_TILE_LIST")
VERSION=$(echo $payload | jq -r ".version")

echo "OPSMAN_IP_ADDRESS : $OPSMAN_IP_ADDRESS"
echo "OPS_MGR_USR : $OPS_MGR_USR"
echo "IAAS : $IAAS"
echo "EXCLUDE_TILE_LIST : $EXCLUDE_TILE_LIST"
echo "VERSION : $VERSION"


#Login into pivnet
pivnet-cli login --api-token="$PIVNET_TOKEN"

# for each version check if it exists, or download it
for version in $(echo $version | jq -r ".version" | jq -r '.[]'); do
    if ls ./bosh-stemcell-$version-$IAAS-hyperv-ubuntu-trusty-go_agent.tgz 1> /dev/null 2>&1; then
        echo "Stemcel $version is already downloaded"
    else
        pivnet download-product-files -p stemcells -r $version -g "*$IAAS*" --accept-eula
    fi
done


result="{\"version\" : $VERSION, \"metadata\" : [] }"
echo $result
#echo $result >&3
